name: Dependabot Auto-assign

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Auto-assign and label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            // Always assign and request review from MitulShah1
            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number: number,
              assignees: ['MitulShah1']
            });
            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number: number,
              reviewers: ['MitulShah1']
            });
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: number,
              labels: ['dependencies', 'automated']
            });
